In [1]:
"""
    It is required to download two files for this module
        - https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv
        - https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n9LOuKI9SlUa1b5zkaCMeg/Product-sales.xlsx
"""
%pip install xlrd openpyxl

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: xlrd, et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [openpyxl]━━━━━━━━━ 2/3 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5 xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [5]:
%pip install pyodide

Collecting pyodide
  Downloading pyodide-0.0.2.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "/usr/local/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.14/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/jv/pcsb941j1db15c2j9vpg4z4m0000gn/T/pip-build-env-48uo1uim/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jv/pcsb941j1db15c2j9vpg4z4m0000gn/T/pip-build-env-48uo1uim/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/private/var/folders/jv/pcsb941j1db15c2j9vpg4z4m0000gn/T/pip-build-env-48uo1uim/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/jv/pcsb941j1db15c2j9vpg4z4m0000gn/T/pip-build-env-48uo1uim/overlay/lib/python3.14/site-packages/setuptools/build_meta.py", line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 7, in <module>
      ValueError: Pyodide is a Python distribution that runs in the browser or Node.js. It cannot be installed from PyPi.
                  See https://github.com/pyodide/pyodide for how to use Pyodide.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'pyodide' when getting requirements to build wheel
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [4]:
# This doesn't run because we are running Jupyter from local Env
from pyodide.http import pyfetch
import pandas as pd

url =  "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"
filename = "Product-sales.csv"

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

await download(url, filename)
df = pd.read_csv(filename)

ModuleNotFoundError: No module named 'pyodide'

In [7]:
df = pd.read_csv("Product-sales.csv")

In [8]:
# Print first five rows of the dataframe

df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [11]:
df = pd.read_excel('Product-sales.xlsx')
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [12]:
# Access to the column Length

x = df[['Quantity']]
x

   Quantity
0         2
1         3
2         5
3        10
4         1

In [15]:
# Get the column as a series

x = df['Product']
x

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: str

In [16]:
# Get the column as a dataframe

x = df[['Quantity']]
type(x)

pandas.DataFrame

In [17]:
# Access to multiple columns

y = df[['Product','Category', 'Quantity']]
y

      Product     Category  Quantity
0      Laptop  Electronics         2
1  Smartphone  Electronics         3
2  Desk Chair    Furniture         5
3    Notebook   Stationery        10
4     Monitor  Electronics         1

In [18]:
# Access the value on the first row and the first column

df.iloc[0, 0]

np.int64(1)

In [19]:
# Access the value on the second row and the first column

df.iloc[1,0]

np.int64(2)

In [20]:
# Access the value on the first row and the third column

df.iloc[0,2]

'Electronics'

In [21]:
# You can access data using loc
print(df.loc[0, 'Product'])
print(df.loc[1, 'Product'])
print(df.loc[1, 'CustomerCity'])
print(df.loc[1, 'Total'])

Laptop
Smartphone
Los Angeles
1800

In [22]:
# Slicing the dataframe

df.iloc[0:2, 0:3]

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics

In [23]:
# Slicing the dataframe using name

df.loc[0:2, 'OrderID':'Category']

   OrderID     Product     Category
0        1      Laptop  Electronics
1        2  Smartphone  Electronics
2        3  Desk Chair    Furniture

In [35]:
new_index=['a','b','c','d','e']
# dir(df)
df_new = df
df_new.index = new_index
df_new.loc['a', 'CustomerCity']

'New York'

In [36]:
df_new.loc['a':'d', 'CustomerCity']

a       New York
b    Los Angeles
c        Chicago
d        Houston
Name: CustomerCity, dtype: str